# A special manual workflow to push a busybox image into our public ghcr. This image is used for the init helper containers
name: Push busybox image to ghcr
on: workflow_dispatch


jobs:
  release:
    name: Push busybox image to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull and Push docker image
        run: |
          cd opensearch-operator
          export IMG=ghcr.io/maibornwolff/opensearch-operator/busybox:1.27.2
          docker buildx build -f Dockerfile-busybox --platform="linux/amd64,linux/arm,linux/arm64" . -t $IMG --push
